# Site settings
title: Jeffrey Neer
description: Jeffrey Neer Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeffreyneer.com"

# User settings
username: Jeffrey Neer
user_description: I'm a Software Engineer from Texas. I am currently updating my main landing page. I should have more info here in the coming days.
user_title: Software Engineer
email: jneer@pm.me
# twitter_username: lorem_ipsum
#instagram_username: lorem_ipsum
#facebook_username: lorem_ipsum
linkedin_username: jeffrey-neer
github_username:  ffejhog
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum
# gplus_username:  lorem_ipsum
blog_url: https://blog.jeffreyneer.com
exclude: ['package.json', 'src' , 'node_modules']
