# Site settings
title: Jeffrey Neer
description: Jeffrey Neer Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jeffrey Neer
user_description: I'm a Software Engineer from Texas. I am currently updating my main landing page. I should have more info here in the coming days.
user_title: Software Engineer
email: jneer@pm.me
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
#linkedin_username: murraco
github_username:  ffejhog
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
